name: project

on:
  issues:
    types:
      - opened
      - transferred
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add Issue or PR to project
    runs-on: ubuntu-latest
    steps:
      - uses: cybozu/octoken-action@v1
        id: create-iat
        with:
          github_app_id: ${{ secrets.PROJECT_GITHUB_APP_ID}}
          github_app_private_key: ${{ secrets.PROJECT_GITHUB_APP_KEY }}
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: ${{ secrets.PROJECT_URL }}
          github-token: ${{ steps.create-iat.outputs.token }}
