packages:
  - "packages/**"
  - "!**/lib/**"
  - "!**/esm/**"
  - "!**/templates/**"

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  # Renovate security update: lodash@4.17.23
  - lodash@4.17.23
