packages:
  - "packages/**"
  - "!**/lib/**"
  - "!**/esm/**"
  - "!**/templates/**"

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  # Renovate security update: lodash@4.17.23
  - lodash@4.17.23
  # Renovate security update: webpack@5.104.1
  - webpack@5.104.1
  # Renovate security update: qs@6.14.2
  - qs@6.14.2
  # Renovate security update: ajv@8.18.0
  - ajv@8.18.0
