import {
    FetchFormPropertiesInput,
    FormsClient,
    FieldTypesOrSubTableFieldTypes,
} from "./forms-client";
import { Promise } from "es6-promise";

export class DemoClient implements FormsClient {
    fetchFormProperties(
        input: FetchFormPropertiesInput
    ): Promise<FieldTypesOrSubTableFieldTypes> {
        const demoResp = {
            properties: [
                {
                    type: "RECORD_NUMBER",
                    label: "Record number",
                    noLabel: "false",
                    code: "Record_number",
                },
                {
                    type: "MODIFIER",
                    label: "Updated by",
                    noLabel: "false",
                    code: "Updated_by",
                },
                {
                    type: "CREATOR",
                    label: "Created by",
                    noLabel: "false",
                    code: "Created_by",
                },
                {
                    type: "UPDATED_TIME",
                    label: "Updated datetime",
                    noLabel: "false",
                    code: "Updated_datetime",
                },
                {
                    type: "CREATED_TIME",
                    label: "Created datetime",
                    noLabel: "false",
                    code: "Created_datetime",
                },
                {
                    type: "SINGLE_LINE_TEXT",
                    label: "Text",
                    noLabel: "false",
                    code: "Text",
                    required: "false",
                    minLength: null,
                    maxLength: null,
                    expression: "",
                    hideExpression: "false",
                    unique: "false",
                    defaultValue: "",
                },
                {
                    type: "RICH_TEXT",
                    label: "Rich text",
                    noLabel: "false",
                    code: "Rich_text",
                    required: "false",
                    defaultValue: "",
                },
                {
                    type: "MULTI_LINE_TEXT",
                    label: "Text area",
                    noLabel: "false",
                    code: "Text_area",
                    required: "false",
                    defaultValue: "",
                },
                {
                    type: "NUMBER",
                    label: "Number",
                    noLabel: "false",
                    code: "Number",
                    required: "false",
                    minValue: null,
                    maxValue: null,
                    digit: "false",
                    unique: "false",
                    defaultValue: null,
                    displayScale: null,
                    unit: null,
                    unitPosition: "BEFORE",
                },
                {
                    type: "CALC",
                    label: "Calculated",
                    noLabel: "false",
                    code: "Calculated",
                    required: "false",
                    expression: "100 + 100",
                    format: "NUMBER",
                    displayScale: null,
                    hideExpression: "false",
                    unit: null,
                    unitPosition: "BEFORE",
                },
                {
                    type: "RADIO_BUTTON",
                    label: "Radio button",
                    noLabel: "false",
                    code: "Radio_button",
                    required: "true",
                    options: ["sample1", "sample2"],
                    defaultValue: "sample1",
                },
                {
                    type: "CHECK_BOX",
                    label: "Check box",
                    noLabel: "false",
                    code: "Check_box",
                    required: "false",
                    options: ["sample1", "sample2"],
                    defaultValue: [],
                },
                {
                    type: "MULTI_SELECT",
                    label: "Multi-choice",
                    noLabel: "false",
                    code: "Multi_choice",
                    required: "false",
                    options: [
                        "sample1",
                        "sample2",
                        "sample3",
                        "sample4",
                    ],
                    defaultValue: [],
                },
                {
                    type: "DROP_DOWN",
                    label: "Drop-down",
                    noLabel: "false",
                    code: "Drop_down",
                    required: "false",
                    options: ["sample1", "sample2"],
                    defaultValue: null,
                },
                {
                    type: "DATE",
                    label: "Date",
                    noLabel: "false",
                    code: "Date",
                    required: "false",
                    unique: "false",
                    defaultValue: null,
                    defaultExpression: "NOW",
                },
                {
                    type: "TIME",
                    label: "Time",
                    noLabel: "false",
                    code: "Time",
                    required: "false",
                    defaultValue: null,
                    defaultExpression: "NOW",
                },
                {
                    type: "DATETIME",
                    label: "Date and time",
                    noLabel: "false",
                    code: "Date_and_time",
                    required: "false",
                    unique: "false",
                    defaultValue: null,
                    defaultExpression: "NOW",
                },
                {
                    type: "FILE",
                    label: "Attachment",
                    noLabel: "false",
                    code: "Attachment",
                    required: "false",
                },
                {
                    type: "LINK",
                    label: "Link",
                    noLabel: "false",
                    code: "Link",
                    required: "false",
                    protocol: "MAIL",
                    minLength: null,
                    maxLength: null,
                    unique: "false",
                    defaultValue: "",
                },
                {
                    type: "USER_SELECT",
                    label: "User selection",
                    noLabel: "false",
                    code: "User_selection",
                    required: "false",
                },
                {
                    type: "ORGANIZATION_SELECT",
                    label: "Department selection",
                    noLabel: "false",
                    code: "Department_selection",
                    required: "false",
                },
                {
                    type: "GROUP_SELECT",
                    label: "Group selection",
                    noLabel: "false",
                    code: "Group_selection",
                    required: "false",
                },
                {
                    type: "REFERENCE_TABLE",
                    label: "関連レコード一覧",
                    noLabel: "true",
                    code: "Related_records",
                    relatedApp: "3",
                },
                {
                    type: "SINGLE_LINE_TEXT",
                    label: "Lookup",
                    noLabel: "false",
                    code: "Lookup",
                    required: "false",
                    relatedApp: "7",
                },
                {
                    type: "SINGLE_LINE_TEXT",
                    label: "Lookup",
                    noLabel: "false",
                    code: "Lookup_0",
                    required: "false",
                    relatedApp: "6",
                },
                {
                    type: "SUBTABLE",
                    code: "Table",
                    fields: [
                        {
                            type: "SINGLE_LINE_TEXT",
                            label: "Text",
                            noLabel: "false",
                            code: "Text_0",
                            required: "false",
                            minLength: null,
                            maxLength: null,
                            expression: "",
                            hideExpression: "false",
                            unique: "false",
                            defaultValue: "",
                        },
                        {
                            type: "RICH_TEXT",
                            label: "Rich text",
                            noLabel: "false",
                            code: "Rich_text_1",
                            required: "false",
                            defaultValue: "",
                        },
                        {
                            type: "MULTI_LINE_TEXT",
                            label: "Text area",
                            noLabel: "false",
                            code: "Text_area_1",
                            required: "false",
                            defaultValue: "",
                        },
                        {
                            type: "NUMBER",
                            label: "Number",
                            noLabel: "false",
                            code: "Number_1",
                            required: "false",
                            minValue: null,
                            maxValue: null,
                            digit: "false",
                            unique: "false",
                            defaultValue: null,
                            displayScale: null,
                            unit: null,
                            unitPosition: "BEFORE",
                        },
                        {
                            type: "CALC",
                            label: "Calculated",
                            noLabel: "false",
                            code: "Calculated_1",
                            required: "false",
                            expression: "1 + 1",
                            format: "NUMBER",
                            displayScale: null,
                            hideExpression: "false",
                            unit: null,
                            unitPosition: "BEFORE",
                        },
                    ],
                },
                {
                    type: "SUBTABLE",
                    code: "Table_0",
                    fields: [
                        {
                            type: "RADIO_BUTTON",
                            label: "Radio button",
                            noLabel: "false",
                            code: "Radio_button_0",
                            required: "true",
                            options: ["sample1", "sample2"],
                            defaultValue: "sample1",
                        },
                        {
                            type: "CHECK_BOX",
                            label: "Check box",
                            noLabel: "false",
                            code: "Check_box_1",
                            required: "false",
                            options: ["sample1", "sample2"],
                            defaultValue: [],
                        },
                        {
                            type: "MULTI_SELECT",
                            label: "Multi-choice",
                            noLabel: "false",
                            code: "Multi_choice_1",
                            required: "false",
                            options: [
                                "sample1",
                                "sample2",
                                "sample3",
                                "sample4",
                            ],
                            defaultValue: [],
                        },
                        {
                            type: "DROP_DOWN",
                            label: "Drop-down",
                            noLabel: "false",
                            code: "Drop_down_1",
                            required: "false",
                            options: ["sample1", "sample2"],
                            defaultValue: null,
                        },
                        {
                            type: "DATE",
                            label: "Date",
                            noLabel: "false",
                            code: "Date_1",
                            required: "false",
                            unique: "false",
                            defaultValue: null,
                            defaultExpression: "NOW",
                        },
                        {
                            type: "TIME",
                            label: "Time",
                            noLabel: "false",
                            code: "Time_1",
                            required: "false",
                            defaultValue: null,
                            defaultExpression: "NOW",
                        },
                        {
                            type: "DATETIME",
                            label: "Date and time",
                            noLabel: "false",
                            code: "Date_and_time_1",
                            required: "false",
                            unique: "false",
                            defaultValue: null,
                            defaultExpression: "NOW",
                        },
                    ],
                },
                {
                    type: "SUBTABLE",
                    code: "Table_1",
                    fields: [
                        {
                            type: "FILE",
                            label: "Attachment",
                            noLabel: "false",
                            code: "Attachment_1",
                            required: "false",
                        },
                        {
                            type: "LINK",
                            label: "Link",
                            noLabel: "false",
                            code: "Link_1",
                            required: "false",
                            protocol: "WEB",
                            minLength: null,
                            maxLength: null,
                            unique: "false",
                            defaultValue: "",
                        },
                        {
                            type: "USER_SELECT",
                            label: "User selection",
                            noLabel: "false",
                            code: "User_selection_1",
                            required: "false",
                        },
                        {
                            type: "ORGANIZATION_SELECT",
                            label: "Department selection",
                            noLabel: "false",
                            code: "Department_selection_1",
                            required: "false",
                        },
                        {
                            type: "GROUP_SELECT",
                            label: "Group selection",
                            noLabel: "false",
                            code: "Group_selection_1",
                            required: "false",
                        },
                    ],
                },
                {
                    type: "LABEL",
                    label: "Label",
                },
                {
                    type: "SPACER",
                    elementId: "",
                },
                {
                    type: "HR",
                },
                {
                    type: "HR",
                },
            ],
        };
        return Promise.resolve(
            demoResp.properties as FieldTypesOrSubTableFieldTypes
        );
    }
}
