import createClient from "openapi-fetch";
import type {paths} from "./generated/schema"; // generated by openapi-typescript

const main = async () => {
  const client = createClient<paths>({
    baseUrl: "http://localhost",
    headers: {
      "X-Cybozu-Authorization": "QWRtaW5pc3RyYXRvcjpjeWJvenU="
    },
  });

  // アプリ作成
  const addAppResp = await client.POST("/k/v1/preview/app.json", {body: {name: "my app"}});
  const app = addAppResp.data!.app!;
  // console.log(addAppResp.data!.app);

  // デプロイ
  const deployAppResp = await client.POST("/k/v1/preview/app/deploy.json", {body: {apps: [{app: app}]}});
  // console.log(deployAppResp.data);

  // デプロイ確認
  deploy_check : while (true) {
    const getAppDeployStatusResp = await client.GET("/k/v1/preview/app/deploy.json", {
      params: {
        query: { apps: [app] }
      }
    });
    for (const status of getAppDeployStatusResp.data!.apps!) {
      if (status.app === app && status.status !== "PROCESSING") {
        console.log("deployed!");
        break deploy_check;
      }
    }
    console.log("deploying...");
    await new Promise(resolve => setTimeout(resolve, 500));
  }

  // アプリ情報取得
  const getAppSettingResp = await client.GET("/k/v1/app/settings.json", {params: {query: {app: app}}});
  console.log(getAppSettingResp.data);
}

main();
