name: License

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze:
    name: Analyze the licenses
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@54d513e0b5ff1158f1cf8321108d666a5a6c1fca # v2
      - name: Check out repository
        uses: actions/checkout@v5
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check licenses
        run: |
          pnpm license:analyze
