name: lint

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: Kesin11/actions-timeline@da70beff098ff89b15d279e8bf2f60519a8dadd7 # v2

      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6

      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"

        # To avoid setup-node cache failure.
        # ref. https://github.com/actions/setup-node/issues/1137
      - name: create pnpm cache directory
        shell: bash
        run: mkdir -vp $(pnpm store path --silent)

      - uses: flatt-security/setup-takumi-guard-npm@9a5d797c2085b6326d3a2985c08e3a114b9b88c1 # v1.1.1
        with:
          bot-id: ${{ !github.event.pull_request.head.repo.fork && secrets.TAKUMI_GUARD_BOT_ID || '' }}

      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm lint
