name: test

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  test:
    name: Node.js ${{ matrix.os }} ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
        # To avoid setup-node cache failure.
        # ref. https://github.com/actions/setup-node/issues/1137
      - name: create pnpm cache directory
        shell: bash
        run: mkdir -vp $(pnpm store path --silent)

      - uses: flatt-security/setup-takumi-guard-npm@9a5d797c2085b6326d3a2985c08e3a114b9b88c1 # v1.1.1
        with:
          bot-id: ${{ !github.event.pull_request.head.repo.fork && secrets.TAKUMI_GUARD_BOT_ID || '' }}

      - run: pnpm install --fetch-timeout 900000 --frozen-lockfile
      - run: pnpm build
      - run: pnpm test:ci

  actions-timeline:
    needs: [test]
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - uses: Kesin11/actions-timeline@da70beff098ff89b15d279e8bf2f60519a8dadd7 # v2
